#!/bin/sh
busybox --list | while read TARGET; do busybox ln -sf busybox bin/$TARGET; done
mkdir /mnt
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
ROOT=$(cat /proc/cmdline | sed -e 's/^.*\broot=\([^ ]*\).*$/\1/')
mount $ROOT /mnt
cp modules/*.ko /mnt
sync
exec switch_root /mnt /sbin/init
