#!/bin/sh
CMDLINE="clk_ignore_unused"
dt dtb-to-dtp /sys/firmware/fdt /boot/fdt.dtb.dtp
dt extract-bootargs /boot/fdt.dtb.dtp /boot/bootargs.dtp
dt extract-adt /boot/adt
dt tunables /boot/adt /linux.dtb /boot/tunables.dtp
dt dtb-to-dtp /linux.dtb /boot/fixed.dtp
cat /boot/fixed.dtp /boot/tunables.dtp /boot/bootargs.dtp > /boot/next-stage.dtp
dt dtp-to-dtb /boot/next-stage.dtp /boot/next-stage.dtb
/bin/kexec -fix /Image --dtb=/boot/next-stage.dtb --initrd=/boot/initfs --command-line=$CMDLINE
