#!/bin/bash
set -o errexit
git submodule update --init --recursive
while ! ./g/bin/install-remotes < g/remotes.txt; do sleep 1; done
git submodule foreach --recursive git fetch --all
make -j13 build/done/binutils-gdb/install
make -j13 build/done/gcc/stage1/install
make -j13 build/done/linux/headers/install
make -j13 build/done/glibc/stage1/install
make -j13 build/done/gcc/gcc/install
make -j13 build/done/glibc/glibc/install
make -j13 build/done/busybox/install
make -j13 build/done/kexec-tools/install
make -j13 build/done/ncurses/install
make -j13 build/done/emacs/cross/install
make -j13 build/done/perl/install
make -j13 build/done/libnl/install
make -j13 build/done/memtool/install
make -j13 build/done/libuuid/install
make -j13 build/done/json-c/install
make -j13 build/done/popt/install
make -j13 build/done/libblkid/install
make -j13 build/done/libaio/install
make -j13 build/done/lvm2/install
make -j13 build/done/openssl/install
make -j13 build/done/cryptsetup/install
make -j13 build/done/nvme-cli/install
make -j13 build/done/linux/linux/image
make -j13 build/done/linux/linux/modules
make -j13 build/done/linux/stage2/image
make -j13 build/done/linux/stage2/modules
make -j13 build/done/linux/stage1/image
