#!/bin/sh -x
busybox --list | while read TARGET; do busybox ln -sf busybox bin/$TARGET; done
mount -t proc proc proc
mount -t sysfs sys sys
mount -t configfs configfs sys/kernel/config
mkdir -p /boot
tar xzf /deb.tar.gz
tar xzf /dt.tar.gz
export PATH=/bin:/usr/bin
dt dtb-to-dtp /sys/firmware/fdt /boot/fdt.dtb.dtp
dt extract-bootargs /boot/bootargs.dtp
cat /boot/bootargs.dtp
dt extract-adt /boot/adt
dt tunables /boot/adt /boot/stage2.dtb /boot/tunables.dtp
sleep 10
dt dtb-to-dtp /boot/stage2.dtb /boot/fixed.dtp
sleep 10
cat /boot/fixed.dtp /boot/tunables.dtp /boot/bootargs.dtp > /boot/next-stage.dtp
sleep 10
dt dtp-to-dtb /boot/next-stage.dtp /boot/next-stage.dtb
sleep 10

(dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=7 seek=72 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=6 seek=73 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=5 seek=74 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=4 seek=75 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=3 seek=76 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=2 seek=77 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=1 seek=78 conv=notrunc
 dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=0 seek=79 conv=notrunc) 2>/dev/null

dt dtb-to-dtp /boot/next-stage.dtb /boot/next-stage.dtb.dtp
sleep 10
grep 'reserved-memory' /boot/next-stage.dtb.dtp
sleep 10
grep 'framebuffer' /boot/next-stage.dtb.dtp
sleep 10

# /bin/kexec -fix /m1n1.macho.image --dtb=/boot/fdt
# /bin/kexec -fix /m1n1.macho.image --dtb=/sys/firmware/fdt

/bin/kexec -fix /boot/stage2.image --dtb=/boot/next-stage.dtb
