#!/bin/sh
/bin/busybox find / >> file.list
/bin/busybox --list | while read TARGET; do busybox ln -sf busybox bin/$TARGET; done
export PATH=/bin:/usr/bin:/sbin:/usr/sbin
ln -sf /proc/self/fd/0 /dev/stdin
mkdir -p boot proc sys tmp persist
mount -t proc proc proc
mount -t sysfs sys sys
mount -t debugfs debug sys/kernel/debug
mount -t configfs configfs sys/kernel/config
if [ -e persist/stage ]; then
    stage=$(cat persist/stage)
else
    stage=stage1
fi
exec /bin/init-$stage
