on:
  push:
    branches: [ release ]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get update
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support
    - run: sudo apt-get install qemu-system
    - run: sudo apt-get install gettext
    - run: sudo apt-get install xz-utils
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install libtool-bin
    - run: make -j13 done/toolchain/binutils-gdb/install
    - run: make -j13 done/linux/headers/install
    - run: make -j13 done/userspace/glibc/headers/install
    - run: make -j13 done/toolchain/gcc/gcc/install
    - run: rm -rf build/toolchain/gcc/gcc
    - run: make -j13 done/userspace/glibc/glibc/install
    - run: make -j13 done/toolchain/gcc/libgcc/install
    - run: rm -rf build/toolchain/gcc/libgcc
    - run: rm -rf toolchain/gcc/gcc
    - run: rm -rf toolchain/binutils-gdb/binutils-gdb
    - run: make -j13 done/userspace/ncurses/install
    - run: make -j13 done/userspace/dialog/install
    - run: make -j13 done/userspace/screen/install
    - run: make -j13 done/userspace/procps/install
    - run: make -j13 done/userspace/busybox/install
    - run: make -j13 done/userspace/kexec-tools/install
    - run: make -j13 done/userspace/emacs/cross/install
    - run: make -j13 done/userspace/perl/install
    - run: make -j13 done/userspace/IPC-Run/install
    - run: make -j13 done/userspace/slurp/install
    - run: make -j13 done/userspace/libnl/install
    - run: make -j13 done/userspace/memtool/install
    - run: make -j13 done/userspace/libuuid/install
    - run: make -j13 done/userspace/json-c/install
    - run: make -j13 done/userspace/popt/install
    - run: make -j13 done/userspace/libblkid/install
    - run: make -j13 done/userspace/libaio/install
    - run: make -j13 done/userspace/lvm2/install
    - run: make -j13 done/userspace/openssl/install
    - run: make -j13 done/userspace/cryptsetup/install
    - run: make -j13 done/userspace/dtc/install
    - run: make -j13 done/userspace/wpa_supplicant/install
    - run: make -j13 done/bootloaders/m1n1/install
    - run: make -j13 done/bootloaders/barebox/install
    - run: make -j13 done/bootloaders/u-boot/install
    - run: make -j13 done/bootloaders/grub/install
    - run: make -j13 done/userspace/install
    - run: rm -rf build/userspace
    - run: rm -rf userspace/emacs/emacs
    - run: rm -rf userspace/glibc/glibc
    - run: rm -rf userspace/openssl/openssl
    - run: make -j13 build/linux/pearl.image.macho
    - run: rm -rf build/linux/linux
    - run: rm -rf build/linux/pearl
    - run: rm -rf build/linux/stage2
    - run: make -j3 debian/debootstrap/debootstrap{checkout}
    - run: make -j3 zstd/zstd{checkout}
    - run: make -j3 build/pearl.pl
    - run: make -j3 build/pearl.pl{release}
    - run: make -j3 {release}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
