name: split1
on:
  workflow_dispatch:
  push:
    branches: [ split, split1 ]
  pull_request:
    branches: [ split, split1 ]
jobs:
  toolchain:
    name: toolchain
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: make -j13 build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{artifact}
  libgcc:
    name: libgcc
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make -j13 done/toolchain/gcc/libgcc/install
    - run: make -j13 build/libgcc.tar.zstd{artifact}
  qemu:
    name: qemu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install meson ninja-build
    - run: make -j13 build/qemu.tar.zstd{artifact}
  debian:
    name: debian
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get update
    - run: sudo apt-get -y dist-upgrade
    - run: sudo apt-get install qemu-system-aarch64
    - run: make -j13 build/debian.tar.zstd{artifact}
  glibc:
    name: glibc
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make -j13 done/userspace/glibc/install
    - run: make -j13 build/glibc.tar.zstd{artifact}
  emacs:
    name: emacs
    runs-on: ubuntu-latest
    needs: [ toolchain, glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make -j13 done/userspace/emacs/install
    - run: make -j13 build/emacs.tar.zstd{artifact}
  perl:
    name: perl
    runs-on: ubuntu-latest
    needs: [ toolchain, glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make -j13 done/userspace/perl/install
    - run: make -j13 build/perl.tar.zstd{artifact}
  openssl:
    name: openssl
    runs-on: ubuntu-latest
    needs: [ toolchain, glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make -j13 done/userspace/openssl/install
    - run: make -j13 build/openssl.tar.zstd{artifact}
  busybox:
    name: busybox
    runs-on: ubuntu-latest
    needs: [ toolchain, glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make -j13 done/userspace/busybox/install
    - run: make -j13 build/busybox.tar.zstd{artifact}
  lvm2:
    name: lvm2
    runs-on: ubuntu-latest
    needs: [ toolchain, glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make -j13 done/userspace/lvm2/install
    - run: make -j13 build/lvm2.tar.zstd{artifact}
  wpa_supplicant:
    name: wpa_supplicant
    runs-on: ubuntu-latest
    needs: [ toolchain, glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make -j13 done/userspace/wpa_supplicant/install
    - run: make -j13 build/wpa_supplicant.tar.zstd{artifact}
  rest:
    name: rest
    runs-on: ubuntu-latest
    needs: [ toolchain, libgcc, glibc, emacs, perl, openssl, busybox, lvm2, wpa_supplicant ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/userspace/glibc/checkout
    - run: make build/artifacts/down/libgcc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/libgcc1.tar.zstd
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make build/artifacts/down/emacs1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/emacs1.tar.zstd
    - run: make build/artifacts/down/perl1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/perl1.tar.zstd
    - run: make build/artifacts/down/openssl1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/openssl1.tar.zstd
    - run: make build/artifacts/down/busybox1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/busybox1.tar.zstd
    - run: make build/artifacts/down/lvm21.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/lvm21.tar.zstd
    - run: make build/artifacts/down/wpa_supplicant1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/wpa_supplicant1.tar.zstd
    - run: rm -rf build/userspace/util-linux done/userspace/util-linux
    - run: make -j13 build/rest.tar.zstd{artifact}
  linux_image:
    name: linux.image
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/linux
    - run: make -j13 build/linux/linux.image.zstd{artifact}
  linux_modules:
    name: linux.modules
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/linux
    - run: make -j13 build/linux/linux.modules.zstd{artifact}
  stage2_image:
    name: stage2.image
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/linux
    - run: make -j13 build/linux/stage2.image.zstd{artifact}
  stage2_modules:
    name: stage2.modules
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: rm -rf done/linux
    - run: make -j13 build/linux/stage2.modules.zstd{artifact}
  bootloaders:
    name: bootloaders
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install autopoint lzop
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make build/bootloaders.tar.zstd{artifact}
  pearl:
    name: pearl
    needs: [ toolchain, glibc, emacs, perl, openssl, busybox, lvm2, wpa_supplicant, rest, linux_image, linux_modules, stage2_image, stage2_modules, bootloaders ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl device-tree-compiler qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make build/artifacts/down/glibc1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/glibc1.tar.zstd
    - run: make build/artifacts/down/emacs1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/emacs1.tar.zstd
    - run: make build/artifacts/down/perl1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/perl1.tar.zstd
    - run: make build/artifacts/down/openssl1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/openssl1.tar.zstd
    - run: make build/artifacts/down/busybox1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/busybox1.tar.zstd
    - run: make build/artifacts/down/lvm21.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/lvm21.tar.zstd
    - run: make build/artifacts/down/wpa_supplicant1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/wpa_supplicant1.tar.zstd
    - run: make build/artifacts/down/rest1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/rest1.tar.zstd
    - run: mkdir -p build/linux
    - run: make build/artifacts/down/linux.image1.zstd{}
    - run: zstd -d < build/artifacts/down/linux.image1.zstd > build/linux/linux.image
    - run: make build/artifacts/down/linux.modules1.zstd{}
    - run: zstd -d < build/artifacts/down/linux.modules1.zstd > build/linux/linux.modules
    - run: make build/artifacts/down/stage2.image1.zstd{}
    - run: zstd -d < build/artifacts/down/stage2.image1.zstd > build/linux/stage2.image
    - run: make build/artifacts/down/stage2.modules1.zstd{}
    - run: zstd -d < build/artifacts/down/stage2.modules1.zstd > build/linux/stage2.modules
    - run: make build/artifacts/down/bootloaders1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/bootloaders1.tar.zstd
    - run: touch --reference=done/bootloaders/barebox/configure bootloaders/barebox/barebox.config
    - run: touch --reference=done/bootloaders/u-boot/configure bootloaders/u-boot/u-boot.config
    - run: mkdir -p done/linux/stage2
    - run: mkdir -p done/linux/linux
    - run: make -j13 done/linux/checkout!
    - run: make -j13 done/linux/stage2/copy!
    - run: make -j13 done/linux/linux/copy!
    - run: rm -rf done/gcc/checkout
    - run: make -j13 build/pearl.tar.zstd{artifact}
  pearl-debian:
    name: pearl-debian
    needs: [ toolchain, pearl, debian ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl device-tree-compiler qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make build/artifacts/down/pearl1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/pearl1.tar.zstd
    - run: make build/artifacts/down/debian.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/debian.tar.zstd
    - run: make -j13 done/linux/checkout!
    - run: make -j13 done/linux/stage2/copy!
    - run: make -j13 done/linux/linux/copy!
    - run: make -j13 build/pearl-debian-uncompressed.macho.zst.image
    - run: mv build/pearl-debian-uncompressed.macho.zst.image build/pearl-debian.image
    - run: make -j13 build/pearl-debian.image{artifact}
  video-uboot:
    name: video-uboot
    needs: [ toolchain, bootloaders, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make build/artifacts/down/bootloaders1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/bootloaders1.tar.zstd
    - run: make build/artifacts/down/qemu.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/qemu.tar.zstd
    - run: sudo apt-get install ffmpeg netpbm socat
    - run: touch --reference=done/bootloaders/barebox/configure bootloaders/barebox/barebox.config
    - run: touch --reference=done/bootloaders/u-boot/configure bootloaders/u-boot/u-boot.config
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: make build/video/u-boot.mp4{artifact}
  video-barebox:
    name: video-barebox
    needs: [ toolchain, bootloaders, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make build/artifacts/down/bootloaders1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/bootloaders1.tar.zstd
    - run: make build/artifacts/down/qemu.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/qemu.tar.zstd
    - run: sudo apt-get install ffmpeg netpbm socat
    - run: touch --reference=done/bootloaders/barebox/configure bootloaders/barebox/barebox.config
    - run: touch --reference=done/bootloaders/u-boot/configure bootloaders/u-boot/u-boot.config
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: make build/video/barebox.mp4{artifact}
  video-pearl:
    name: video-pearl
    needs: [ toolchain, pearl, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl device-tree-compiler qemu-user qemu-user-static binfmt-support autopoint gettext libtool-bin
    - run: make build/artifacts/down/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/toolchain.tar.zstd
    - run: make build/artifacts/down/pearl1.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/pearl1.tar.zstd
    - run: make build/artifacts/down/qemu.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/qemu.tar.zstd
    - run: sudo apt-get install ffmpeg netpbm socat
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: mkdir -p done/linux/stage2
    - run: mkdir -p done/linux/linux
    - run: make -j13 done/linux/checkout!
    - run: make -j13 done/linux/stage2/copy!
    - run: make -j13 done/linux/linux/copy!
    - run: make -j13 done/glibc/checkout!
    - run: make -j13 done/glibc/glibc/copy!
    - run: make --trace build/video/pearl.mp4{artifact}
  video-debian:
    name: video-debian
    needs: [ toolchain, pearl-debian, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/released/pipcet/pearl-toolchain/toolchain.tar.zstd{}
    - run: tar --skip-old-files -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make build/artifacts/down/pearl-debian1.image{}
    - run: mv build/artifacts/down/pearl-debian1.image build/pearl-debian-uncompressed.macho.zst.image
    - run: make build/artifacts/down/qemu.tar.zstd{}
    - run: tar --skip-old-files -xf build/artifacts/down/qemu.tar.zstd
    - run: sudo apt-get install ffmpeg netpbm socat
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: make build/video/pearl-debian.mp4{artifact}
