name: split1
on:
  workflow_dispatch:
  push:
    branches: [ split1 ]
  pull_request:
    branches: [ split1 ]
env:
  RELEASED_ARTIFACTS: toolchain rootfs udeb installer debian
  BUILDER: 1
jobs:
  toolchain:
    name: toolchain
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/toolchain.tar.zstd{artifact}
  qemu:
    name: qemu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/qemu.tar.zstd{artifact}
  rootfs:
    name: rootfs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/debian-rootfs/root2.cpio.zstd{artifact}
  bootloaders:
    name: bootloaders
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make build/bootloaders.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  glibc:
    name: glibc
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/glibc.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  linux_image:
    name: linux.image
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/linux/linux.image.zstd{artifact} build/linux/linux.dtbs.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  linux_modules:
    name: linux.modules
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/linux/linux.modules.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  stage2_image:
    name: stage2.image
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/linux/stage2.image.zstd{artifact} build/linux/stage2.dtbs.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  stage2_modules:
    name: stage2.modules
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/linux/stage2.modules.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  libgcc:
    name: libgcc
    runs-on: ubuntu-latest
    needs: [ toolchain ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/libgcc.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd
  debian:
    name: debian
    runs-on: ubuntu-latest
    needs: [ rootfs ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian.cpio.zstd{artifact}
      env:
        ARTIFACTS: root2.cpio.zstd
  debian-nobootloader:
    name: debian-nobootloader
    runs-on: ubuntu-latest
    needs: [ rootfs ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/installer/packages/nobootloader.udeb.zstd{artifact}
      env:
        ARTIFACTS: root2.cpio.zstd
  debian-partman-auto:
    name: debian-partman-auto
    runs-on: ubuntu-latest
    needs: [ rootfs ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/installer/packages/partman-auto.udeb.zstd{artifact}
      env:
        ARTIFACTS: root2.cpio.zstd
  debian-user-setup:
    name: debian-user-setup
    runs-on: ubuntu-latest
    needs: [ rootfs ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/installer/packages/user-setup.udeb.zstd{artifact}
      env:
        ARTIFACTS: root2.cpio.zstd
  debian-netcfg-static:
    name: debian-netcfg-static
    runs-on: ubuntu-latest
    needs: [ rootfs ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/installer/packages/netcfg.udeb.zstd{artifact}
      env:
        ARTIFACTS: root2.cpio.zstd
  debian-libdebian-installer:
    name: debian-libdebian-installer
    runs-on: ubuntu-latest
    needs: [ rootfs ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/installer/packages/libdebian-installer.udeb.zstd{artifact}
      env:
        ARTIFACTS: root2.cpio.zstd
  video-uboot:
    name: video-uboot
    needs: [ bootloaders, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/video/u-boot.mp4{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd bootloaders.tar.zst qemu.tar.zstd
  video-barebox:
    name: video-barebox
    needs: [ bootloaders, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/video/barebox.mp4{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd bootloaders.tar.zst qemu.tar.zstd
  emacs:
    name: emacs
    runs-on: ubuntu-latest
    needs: [ glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/emacs.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd
  perl:
    name: perl
    runs-on: ubuntu-latest
    needs: [ glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/perl.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd
  openssl:
    name: openssl
    runs-on: ubuntu-latest
    needs: [ glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/openssl.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd
  busybox:
    name: busybox
    runs-on: ubuntu-latest
    needs: [ glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/busybox.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd
  lvm2:
    name: lvm2
    runs-on: ubuntu-latest
    needs: [ glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/lvm2.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd
  wpa_supplicant:
    name: wpa_supplicant
    runs-on: ubuntu-latest
    needs: [ glibc ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/wpa_supplicant.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd
  installer:
    name: installer
    runs-on: ubuntu-latest
    needs: [ debian-partman-auto, debian-netcfg-static, debian-user-setup, debian-libdebian-installer, debian-nobootloader ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/debian/installer/installer.cpio.zstd{artifact}
      env:
        ARTIFACTS: partman-auto.udeb.zstd netcfg.udeb.zstd user-setup.udeb.zstd libdebian-installer.udeb.zstd nobootloader.udeb.zstd
  rest:
    name: rest
    runs-on: ubuntu-latest
    needs: [ libgcc, emacs, perl, openssl, busybox, lvm2, wpa_supplicant ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/rest.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd glibc.tar.zstd libgcc.tar.zstd emacs.tar.zstd perl.tar.zstd openssl.tar.zstd busybox.tar.zstd lvm2.tar.zstd wpa_supplicant.tar.zstd
  dplusi:
    name: dplusi
    runs-on: ubuntu-latest
    needs: [ debian, installer ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/dplusi.tar.zstd{artifact}
      env:
        ARTIFACTS: debian.cpio.zstd installer.cpio.zstd
  pearl:
    name: pearl
    needs: [ rest, linux_image, linux_modules, stage2_image, stage2_modules, bootloaders ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/pearl.tar.zstd{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd rest.tar.zstd linux.image.zstd linux.modules.zstd linux.dtbs.zstd stage2.image.zstd stage2.modules.zstd stage2.dtbs.zstd glibc.tar.zstd libgcc.tar.zstd emacs.tar.zstd perl.tar.zstd openssl.tar.zstd busybox.tar.zstd lvm2.tar.zstd wpa_supplicant.tar.zstd rest.tar.zstd bootloaders.tar.zstd
  pearl-debian:
    name: pearl-debian
    needs: [ pearl, dplusi ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/pearl-debian.image{artifact}
      env:
        ARTIFACTS: pearl.tar.zstd dplusi.tar.zstd
  video-pearl:
    name: video-pearl
    needs: [ pearl, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/video/pearl.mp4{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd qemu.tar.zstd linux.image.zstd pearl.tar.zstd
  video-debian:
    name: video-debian
    needs: [ pearl-debian, qemu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: make -j13 build/video/pearl-debian.mp4{artifact}
      env:
        ARTIFACTS: toolchain.tar.zstd pearl-debian.image qemu.tar.zstd
