name: barebox video
on:
  workflow_dispatch:
  push:
    branches: [ main, dcp, update, video ]
  pull_request:
    branches: [ main, dcp, update, video ]
jobs:
  video-barebox:
    name: barebox video
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - run: make -j13 build/released/pipcet/pearl-bootloaders/bootloaders.tar.zstd
    - run: zstd -d < build/released/pipcet/pearl-bootloaders/bootloaders.tar.zstd | tar --strip-components 6 -xv
    - run: make qemu/qemu{checkout}
    - run: make toolchain/binutils-gdb/binutils-gdb{checkout}
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get update
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support
    - run: sudo apt-get install qemu-system-arm
    - run: sudo apt-get install sharutils
    - run: sudo apt-get install gettext
    - run: sudo apt-get install xz-utils
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install libtool-bin
    - run: sudo apt-get install ffmpeg
    - run: sudo apt-get install vncsnapshot
    - run: sudo apt-get install netpbm
    - run: sudo apt-get install ninja-build
    - run: sudo apt-get install meson
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: make -j13 done/toolchain/binutils-gdb/install
    - run: make -j13 done/qemu/build
    - run: mkdir -p done/bootloaders/barebox
    - run: touch done/bootloaders/barebox/checkout
    - run: touch done/bootloaders/barebox/copy
    - run: touch done/bootloaders/barebox/build
    - run: touch done/bootloaders/barebox/install
    - run: touch build/initramfs/pearl/boot/barebox.image
    - run: make -j13 build/initramfs/pearl/boot/barebox.image.mp4{artifact}
