include userspace/glibc/glibc.mk
include userspace/busybox/busybox.mk
include userspace/kexec-tools/kexec-tools.mk
include userspace/lvm2/lvm2.mk
include userspace/nvme-cli/nvme-cli.mk
include userspace/memtool/memtool.mk
include userspace/ncurses/ncurses.mk
include userspace/emacs/emacs.mk
include userspace/perl/perl.mk
include userspace/libnl/libnl.mk
include userspace/cryptsetup/cryptsetup.mk
include userspace/util-linux/util-linux.mk
include userspace/json-c/json-c.mk
include userspace/popt/popt.mk
